version: '3.8'

services:
  #configmanager:
  #  build:
  #    context: ..
  #    dockerfile: docker/Api.Dockerfile
  #  container_name: configmanager_api
  #  ports:
  #    - "8081:8081"
  #  restart: always
  #  environment:
  #    Application__Name: "SERVICE-A"
  #    MongoDB__ConnectionString: "mongodb://mongo:27017"
  #    CONFIG_MANAGER_PORT: "8081"
  #    RabbitMQ__ConnectionString: "amqp://guest:guest@rabbitmq:5672/"
  #  depends_on:
  #    - mongo
  #    - rabbitmq
  #  networks:
  #    - configmanager_network 
#
  #client:
  #  build:
  #    context: ..
  #    dockerfile: docker/Client.Dockerfile
  #  container_name: blazor_client
  #  restart: always
  #  ports:
  #    - "5001:80"
  #  depends_on:
  #    - configmanager
  #    - mongo
  #    - rabbitmq
  #  networks:
  #    - configmanager_network  

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MongoDB__ConnectionString: "mongodb://mongo:27017"
      ConfigManagerDB: "ConfigManagerDB"
    networks:
      - configmanager_network 

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - configmanager_network 
  

networks:
  configmanager_network: 
    driver: bridge
